name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: jagerzhang/opentelemetry-python-contrib
          token: ${{ secrets.GITHUB_TOKEN }}
          path: your-fork

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/open-telemetry/opentelemetry-python-contrib.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
